#!/usr/bin/python3
import turtle
def circle(color,r):
  turtle.fillcolor(color)
  turtle.begin_fill()
  turtle.circle(r)
  turtle.end_fill()
turtle.penup()
turtle.goto(0,-100)
turtle.pendown()
circle('yellow', 100)
turtle.penup()
turtle.goto(-35, 30)
turtle.pendown()
circle('blue', 12)
turtle.penup()
turtle.goto(35, 30)
turtle.pendown()
circle('blue', 12)
turtle.pensize(10)
turtle.penup()
turtle.goto(0,-20)
turtle.pendown()
turtle.left(90)
turtle.forward(30)
turtle.pencolor('red')
turtle.penup()
turtle.goto(-50,-35)
turtle.pendown()
turtle.left(180)
turtle.circle(50,180)


